### ISSUE TITLE
Nested JSON

### ISSUE THREAD

**Issue by yshemesh** [fukuiretu/fluent-plugin-mysql-load#8]
It would be very useful to support nested JSON, so the database column name will be named as the JSON parent key name suffixed with "." and then the specific nested keys. for example:
{ count: 123123, people: {first: 'john', last: 'doe'} }

==>

count, people.first, people.last

**Comment by fukuiretu** [comment]
Hi, @yshemesh 

I think that I can be using [fluent-plugin-record-reformer](https://github.com/sonots/fluent-plugin-record-reformer). However, there is a possibility that does not work depending on the version of fluentd.

Anyway it does not support in this plugin.
